# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rakuna 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rakuna"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Chris Olstrom"]
  s.date = "2015-11-30"
  s.description = "Rakuna provides mixins to simplify Webmachine development"
  s.email = "chris@olstrom.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "gem_graph.png",
    "lib/rakuna.rb",
    "rakuna.gemspec",
    "spec/rakuna_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/colstrom/rakuna"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Reusable Mixins for Webmachine-powered Applications"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rakuna-core>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rakuna-content-json>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rakuna-data-redis>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rakuna-integration-github>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rakuna-session-redis>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rakuna-content-signature>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rakuna-authentication-github>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rakuna-validation-json>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.4"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<bundler>, ["~> 1.10"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_development_dependency(%q<reek>, ["~> 3.7"])
      s.add_development_dependency(%q<roodi>, ["~> 5.0"])
      s.add_development_dependency(%q<flog>, ["~> 4.3"])
      s.add_development_dependency(%q<rubocop>, ["~> 0.35"])
      s.add_development_dependency(%q<inch>, ["~> 0.7"])
    else
      s.add_dependency(%q<rakuna-core>, ["~> 1.0"])
      s.add_dependency(%q<rakuna-content-json>, ["~> 1.0"])
      s.add_dependency(%q<rakuna-data-redis>, ["~> 1.0"])
      s.add_dependency(%q<rakuna-integration-github>, ["~> 1.0"])
      s.add_dependency(%q<rakuna-session-redis>, ["~> 1.0"])
      s.add_dependency(%q<rakuna-content-signature>, ["~> 1.0"])
      s.add_dependency(%q<rakuna-authentication-github>, ["~> 1.0"])
      s.add_dependency(%q<rakuna-validation-json>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, ["~> 3.4"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<bundler>, ["~> 1.10"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_dependency(%q<reek>, ["~> 3.7"])
      s.add_dependency(%q<roodi>, ["~> 5.0"])
      s.add_dependency(%q<flog>, ["~> 4.3"])
      s.add_dependency(%q<rubocop>, ["~> 0.35"])
      s.add_dependency(%q<inch>, ["~> 0.7"])
    end
  else
    s.add_dependency(%q<rakuna-core>, ["~> 1.0"])
    s.add_dependency(%q<rakuna-content-json>, ["~> 1.0"])
    s.add_dependency(%q<rakuna-data-redis>, ["~> 1.0"])
    s.add_dependency(%q<rakuna-integration-github>, ["~> 1.0"])
    s.add_dependency(%q<rakuna-session-redis>, ["~> 1.0"])
    s.add_dependency(%q<rakuna-content-signature>, ["~> 1.0"])
    s.add_dependency(%q<rakuna-authentication-github>, ["~> 1.0"])
    s.add_dependency(%q<rakuna-validation-json>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, ["~> 3.4"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<bundler>, ["~> 1.10"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.11"])
    s.add_dependency(%q<reek>, ["~> 3.7"])
    s.add_dependency(%q<roodi>, ["~> 5.0"])
    s.add_dependency(%q<flog>, ["~> 4.3"])
    s.add_dependency(%q<rubocop>, ["~> 0.35"])
    s.add_dependency(%q<inch>, ["~> 0.7"])
  end
end

